name: Release Preview
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install --save-dev semantic-release semantic-release-github-pr@6.0.0
      - run: DEBUG=semantic-release:* npx semantic-release-github-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
